# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HealthLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='carbohydrate_in_grams',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='fat_in_grams',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='protein_in_grams',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='food',
            name='diet_label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.DietLabel'),
        ),
        migrations.AddField(
            model_name='food',
            name='health_label',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='food.HealthLabel'),
            preserve_default=False,
        ),
    ]
