# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20160315_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='diet_label',
        ),
        migrations.AddField(
            model_name='food',
            name='diet_label',
            field=models.ManyToManyField(to='food.DietLabel'),
        ),
        migrations.RemoveField(
            model_name='food',
            name='health_label',
        ),
        migrations.AddField(
            model_name='food',
            name='health_label',
            field=models.ManyToManyField(to='food.HealthLabel'),
        ),
    ]
