# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='FoodUser',
        ),
    ]
