# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20160316_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooduser',
            name='max_cal',
            field=models.FloatField(default=0),
        ),
    ]
