# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_food_meal_time'),
        ('food', '0006_fooduser_max_cal'),
    ]

    operations = [
    ]
