# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='fooduser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='history',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.FoodUser', to_field='email'),
        ),
        migrations.AddField(
            model_name='history',
            name='foods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food'),
        ),
    ]
