# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20160318_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='email',
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.FoodUser'),
        ),
    ]
