# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20160318_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooduser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
